Catchup with github action fixes

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,6 +1,9 @@
 name: Maven Build
 
 on:
+  push:
+    branches:
+      - 'wip/**'
   pull_request:
     branches: [ "master" ]
   merge_group:
@@ -14,10 +17,18 @@ jobs:
     strategy:
       fail-fast: true
       matrix:
-        java: [ 8, 11, 17, 21 ]
+        java: [ 8, 11 ]
         experimental: [false]
+        include:
+          - java: 17
+            experimental: true
     steps:
     - uses: actions/checkout@v3
+    - name: Prevent wip merge
+      if: github.event_name == 'pull_request' && startsWith(github.head_ref, 'wip/')
+      run: |
+        echo "::error::WIP branches cannot be merged"
+        exit 1
     - name: Set up JDK ${{ matrix.java }}
       uses: actions/setup-java@v3
       with:
